In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [3]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [4]:
def deriveSig(z):
    return sigmoid(z) * (1-sigmoid(z))

# Forward Propagation without Hidden Layer

In [5]:
#no hidden layer weights
weights = 2*np.random.random((2,1))-1
bias = 2*np.random.random(1)-1
lr = 0.1
weights,bias

(array([[-0.80785379],
        [-0.88398097]]), array([0.30025405]))

In [6]:
#forward propagation without any hidden layer
output0 = X
output = sigmoid(np.dot(output0,weights)+bias)

# Backward Propagation

In [7]:
#forward propagation without any hidden layer
output0 = X
output = sigmoid(np.dot(output0,weights)+bias)

#Back Propagation using Gradient descent
for i in range(10000):
    first_term = output-Y
    input_last_layer = np.dot(output0,weights)+bias
    second_term = deriveSig(input_last_layer)
    first_two = first_term * second_term

    changes = np.array([[0.0],[0.0]])

    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0]*output0[j][i]

    weights -= lr*changes 
    bias_changes = 0.0
    for j in range(4):
        bias_changes += first_two[j][0]*1

    bias -= lr*bias_changes

output = sigmoid(np.dot(X,weights)+bias)
weights,bias,output

(array([[8.61991797],
        [8.67019961]]), array([-12.73924087]), array([[2.93370683e-06],
        [1.68064829e-02],
        [1.59955022e-02],
        [9.89552361e-01]]))

In [8]:
#forward propagation without any hidden layer
output0 = X
output = sigmoid(np.dot(output0,weights)+bias)

#Back Propagation using Gradient descent(optimised)
for i in range(10000):
    first_term = output-Y
    input_last_layer = np.dot(output0,weights)+bias
    second_term = deriveSig(input_last_layer)
    first_two = first_term * second_term

    changes = np.array([[0.0],[0.0]])

    changes = output0.T.dot(first_two)
    weights -= lr*changes 
    bias_changes = 0.0

    bias_changes = first_two.sum()

    bias -= lr*bias_changes

output = sigmoid(np.dot(X,weights)+bias)
weights,bias,output

(array([[8.55367266],
        [8.58477193]]), array([-13.0314487]), array([[2.19034632e-06],
        [1.15817338e-02],
        [1.12310764e-02],
        [9.83809313e-01]]))

# Forward Propagation with hidden layer

In [23]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [24]:
wh = 2*np.random.random((2,2))-1
bh = 2*np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1))-1
lr = 0.1

In [25]:
output0 = X
outputHidden = sigmoid(np.dot(output0,wh)+bh)
output = sigmoid(np.dot(outputHidden,wo)+bo)

#first_term = outputHidden
output

array([[0.51343322],
       [0.49053515],
       [0.48609488],
       [0.46316164]])

# Backward Propagation

In [26]:
for i in range(10000):
    output0 = X
    inputHidden = np.dot(output0,wh)+bh
    outputHidden = sigmoid(inputHidden)
    inputForOutputLayer = np.dot(outputHidden,wo)+bo
    output = sigmoid(inputForOutputLayer)

    first_term_Output_layer = output-Y
    second_term_Output_layer = deriveSig(inputForOutputLayer)
    first_two_Output_layer = first_term_Output_layer*second_term_Output_layer

    first_term_hidden_layer = np.dot(first_two_Output_layer,wo.T)
    second_term_hidden_layer = deriveSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer

    changes_output_layer = np.dot(outputHidden.T,first_two_Output_layer)
    changes_output_bias = np.sum(first_two_Output_layer,axis = 0,keepdims = True)

    changes_hidden_layer = np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer,axis = 0,keepdims = True)

    wo = wo-lr*changes_output_layer
    bo = bo-lr*changes_output_bias

    wh = wh-lr*changes_hidden_layer
    bh = bh-lr*changes_hidden_bias
    
output0 = X
inputHidden = np.dot(output0,wh)+bh
outputHidden = sigmoid(inputHidden)
inputForOutputLayer = np.dot(outputHidden,wo)+bo
output = sigmoid(inputForOutputLayer)

output,wh,bh,wo,bo

(array([[0.07905139],
        [0.93229502],
        [0.93229442],
        [0.06807092]]), array([[4.36942575, 4.88219012],
        [4.35427161, 4.85978784]]), array([[-6.75204801, -2.07003465]]), array([[-7.08758752],
        [ 6.81891807]]), array([[-3.21105008]]))