In [24]:
import math as m
math.sqrt(10)

NameError: name 'math' is not defined

In [1]:
# Numpy arrays will have elements of same type
import numpy as np

In [49]:
# creating numpy arrays
l = [1,2,3]
print(np.array(l))

l1 = [1,2,"3"]
print(np.array(l1))      # since 3 is a string therefore it will convert the whole array into a string

# using helper functions to create numpy arrays
a = np.zeros(10,int)          # creates an array with all zeros. by default the array have all float values
b = np.ones((2,3,2))       # creates an array with all ones. by default the array have all integer values

print(a.dtype)            # tells us what is the datatype of this array
print(type(a))

print(b.dtype)            # tells us what is the datatype of this array
print(type(b))

# Multidimensional Arrays
print(np.zeros((2,3)))          # so to create a 2-D array we can give it two arguments in the form of a single tuple that i want the array to be of 2 * 3 size

[1 2 3]
['1' '2' '3']
int32
<class 'numpy.ndarray'>
float64
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]


In [52]:
a[0] = "1"
print(a)     # a[0] = "1" got converted into integer cutomatically
# a[0] = "sa"    # NOT VALID as string "sa" cannot be converted to an integer

print(a[2:4])

print(b.shape)      # shape is basically the size of the array
print(a.shape)      # here the output is (10,) which means that we have 10 rows and 1 column

[1 0 0 0 0 0 0 0 0 0]
[0 0]
(2, 3, 2)
(10,)


In [66]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0])
print()
print(a[:,0])         # it means that i want every row because of : sign and only the 0th column. could also do like
                      # print(a[:,0:2]) it means that i want all the rows but in columns i want it from 0 to 2 i.e. 0 and 1 as 2 being non-inclusive

[1 2 3]

[1 4]


In [70]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [72]:
a = np.array([0, 1, 2, 3])
print(a.shape)

(4,)


# Numpy Operations

In [18]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a + 2)       # 2 gets added to every element in the array
print(a + b)
print(a * 2)
print(a * b)
print(a ** 2)
print(a ** b)      # it means 1 ** 5, 2 ** 6, 3 ** 7

[3 4 5]
[ 6  8 10]
[2 4 6]
[ 5 12 21]
[1 4 9]
[   1   64 2187]


In [21]:
print(a.mean())     # gives the mean of the array a
print(a.sum())      # gives the sum of the array a

2.0
6


In [27]:
a = np.array([1,2,3])
b = np.array([5,6,7])
# find the distance between two points using a and b
d = ((a - b) ** 2).sum()
distance = m.sqrt(d)
print(distance)

6.928203230275509


In [31]:
x = np.array([1,3,5,6])
xFromMean = ((x-x.mean())**2).sum()
print(xFromMean)

14.75


In [34]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])

a1.dot(a2)          # dot product of a1 and a2

array([[ 70, 100],
       [150, 220]])

In [38]:
# np.mat()    # matrices classes in numpy. almost like 2-D Arrays. numpy matrices are actually a subclass of numpy arrays and they are strictly 2-D
# so if two numpy matrices a and b are there then doing a * b is actually going to take their product rather than normal multiplication

In [47]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 3, 4, 5])
a.dot(b)

26

In [48]:
a = np.matrix('1 2 4; 3 4 5')
a.shape

(2, 3)

In [59]:
np.sum([[0, 1], [0, 5]], axis=1)   
# axis = 0 means that the sum will be calculated along the column and axis = 1 means the sum will be calculated along the row

array([1, 5])

In [24]:
string = input().strip().split(" ")
n = int(string[0])
m = int(string[1])
l = [int(i) for i in input().strip().split(" ")]
array = [[l[i * m + j] for j in range(m)] for i in range(n)]
print(array)
startIndexRow = 0
endIndexRow = n-1
startIndexCol = 0
endIndexCol = m-1
c = 1
totalElements = n * m
while c <= totalElements:
    for j in range(startIndexCol,endIndexCol + 1):
        if c <= totalElements:
            print(array[startIndexRow][j], end = " ")
            c += 1
    startIndexRow += 1
    
    
    for i in range(startIndexRow,endIndexRow + 1):
        if c <= totalElements:
            print(array[i][endIndexCol], end = " ")
            c += 1
    endIndexCol -= 1
    
    
    for j in range(endIndexCol,startIndexCol - 1,-1):
        if c <= totalElements:
            print(array[endIndexRow][j], end = " ")
            c += 1
    endIndexRow -= 1
    
    
    for i in range(endIndexRow,startIndexRow - 1,-1):
        if c <= totalElements:
            print(array[i][startIndexCol], end = " ")
            c += 1
    startIndexCol += 1

2 3
1 2 3 4 5 6
[[1, 2, 3], [4, 5, 6]]
1 2 3 6 5 4 

In [31]:
string = input().strip().split(" ")
l = [int(i) for i in string]
l = l[2:]
n = int(string[0])
m = int(string[1])
array = [[l[i * m + j] for j in range(m)] for i in range(n)]
print(array)
startIndexRow = 0
endIndexRow = n-1
startIndexCol = 0
endIndexCol = m-1
c = 1
totalElements = n * m
while c <= totalElements:
    for j in range(startIndexCol,endIndexCol + 1):
        if c <= totalElements:
            print(array[startIndexRow][j], end = " ")
            c += 1
    startIndexRow += 1
    
    
    for i in range(startIndexRow,endIndexRow + 1):
        if c <= totalElements:
            print(array[i][endIndexCol], end = " ")
            c += 1
    endIndexCol -= 1
    
    
    for j in range(endIndexCol,startIndexCol - 1,-1):
        if c <= totalElements:
            print(array[endIndexRow][j], end = " ")
            c += 1
    endIndexRow -= 1
    
    
    for i in range(endIndexRow,startIndexRow - 1,-1):
        if c <= totalElements:
            print(array[i][startIndexCol], end = " ")
            c += 1
    startIndexCol += 1

4 5 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
1 2 3 4 5 10 15 20 19 18 17 16 11 6 7 8 9 14 13 12 

In [7]:
a = np.array([[1,2,3,4,5],[5,4,2,3,1]])
print(a)
a[5] = 1

[[1 2 3 4 5]
 [5 4 2 3 1]]


IndexError: index 5 is out of bounds for axis 0 with size 2